apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
spec:
  serviceName: "storage"
  updateStrategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: gcr.io/bright-benefit-457321-n8/storage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: storage-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  clusterIP: 34.118.224.1
  selector:
    app: storage
  ports:
    - port: 8080
      targetPort: 3000
